---
- hosts: routers
  become: yes      #to use enable

  tasks:
    - name: Create Loopback888
      cisco.ios.ios_interfaces:
        config:
          - name: Loopback888
            description: Created loopback
            enabled: true

    - name: Add IP address to L888
      cisco.ios.ios_l3_interface:
        name: Loopback888
        ipv4: 192.18.255.88/32